sudo: required
services:
  - docker

before_install:
  - docker build -t emilerodenbach/docker-react -f Dockerfile.dev .

scripts:
  - docker run emilerodenbach/docker-react npm run test -- --coverage